# Generated by Django 4.1.2 on 2023-09-18 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testdata',
            name='is_enable',
            field=models.BooleanField(default=False),
        ),
    ]
